spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: db.charity.in/charityapp_category_db
        username: prod_user
        password: prod_user 
    flyway: 
        driverClassName: com.mysql.cj.jdbc.Driver
        url: db.charity.in/charityapp_category_db
        username: prod_user
        password: prod_user