spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql:// devdb.charityapp.in:3306/charityapp_category_db
        username: dev_user
        password: dev_user 
    flyway: 
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql:// devdb.charityapp.in:3306/charityapp_category_db
        username: dev_user
        password: dev_user